# Generated by Django 3.0.4 on 2020-03-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='searches',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
